export const headers = {
  v2: [
    { name: "asset", key: "symbol" },
    { name: "frozen", key: "frozen" },
    { name: "paused", key: "paused" },
    { name: "can collateral", key: "canCollateral" },
    { name: "LTV", key: "LTV", isPercent: true },
    { name: "liquidation thereshold", key: "liqThereshold", isPercent: true },
    { name: "liquidation bonus", key: "liqBonus", isPercent: true },
    { name: "reserve factor", key: "reserveFactor", isPercent: true },
    { name: "can borrow", key: "canBorrow" },
    { name: "optimal utilization", key: "optimalUtilization", isPercent: true },
    { name: "variable borrow rate", key: "varBorrowRate", isPercent: true },
    { name: "can borrow stable", key: "canBorrowStable" },
    { name: "stable borrow rate", key: "stableBorrowRate", isPercent: true },
    { name: "share of stable rate", key: "shareOfStableRate", isPercent: true },
    { name: "", key: "assetLink" },
  ],
  v3: [
    { name: "asset", key: "symbol" },
    { name: "frozen", key: "frozen" },
    { name: "paused", key: "paused" },
    { name: "can collateral", key: "canCollateral" },
    { name: "LTV", key: "LTV", isPercent: true },
    { name: "liquidation thereshold", key: "liqThereshold", isPercent: true },
    { name: "liquidation bonus", key: "liqBonus", isPercent: true },
    { name: "reserve factor", key: "reserveFactor", isPercent: true },
    { name: "can borrow", key: "canBorrow" },
    { name: "optimal utilization", key: "optimalUtilization", isPercent: true },
    { name: "variable borrow rate", key: "varBorrowRate", isPercent: true },
    { name: "can borrow stable", key: "canBorrowStable" },
    { name: "stable borrow rate", key: "stableBorrowRate", isPercent: true },
    { name: "share of stable rate", key: "shareOfStableRate", isPercent: true },
    { name: "is isolated", key: "isIsolated" },
    { name: "debt ceiling", key: "debtCeiling" },
    { name: "supply cap", key: "supplyCap" },
    { name: "borrow cap", key: "borrowCap" },
    { name: "emode LTV", key: "eModeLtv", isPercent: true },
    {
      name: "emode liq thereshold",
      key: "eModeLiquidationThereshold",
      isPercent: true,
    },
    { name: "emode liq bonus", key: "eModeLiquidationBonus", isPercent: true },
    { name: "borrowable in iso mode", key: "borrowableInIsoMode" },
    { name: "flashloan enabled", key: "flashloanEnabled" },
    { name: "", key: "assetLink" },
  ],
  zerolend: [
    { name: "asset", key: "symbol" },
    { name: "frozen", key: "frozen" },
    { name: "paused", key: "paused" },
    { name: "collateral?", key: "canCollateral" },
    { name: "LTV", key: "LTV", isPercent: true },
    { name: "liquidation thereshold", key: "liqThereshold", isPercent: true },
    { name: "liquidation bonus", key: "liqBonus", isPercent: true },
    { name: "reserve factor", key: "reserveFactor", isPercent: true },
    { name: "can borrow", key: "canBorrow" },
    { name: "optimal utilization", key: "optimalUtilization", isPercent: true },
    { name: "variable borrow rate", key: "varBorrowRate", isPercent: true },
    { name: "can borrow stable", key: "canBorrowStable" },
    { name: "stable borrow rate", key: "stableBorrowRate", isPercent: true },
    { name: "share of stable rate", key: "shareOfStableRate", isPercent: true },
    { name: "is isolated", key: "isIsolated" },
    { name: "debt ceiling", key: "debtCeiling" },
    { name: "supply cap", key: "supplyCap" },
    { name: "borrow cap", key: "borrowCap" },
    { name: "emode LTV", key: "eModeLtv", isPercent: true },
    {
      name: "emode liq thereshold",
      key: "eModeLiquidationThereshold",
      isPercent: true,
    },
    { name: "emode liq bonus", key: "eModeLiquidationBonus", isPercent: true },
    { name: "borrowable in iso mode", key: "borrowableInIsoMode" },
    { name: "flashloan enabled", key: "flashloanEnabled" },
    { name: "", key: "assetLink" },
  ],
  benqi: [
    { name: "asset", key: "symbol" },
    { name: "collateral factor", key: "collateralFactor", isPercent: true },
    { name: "reserve factor", key: "reserveFactor", isPercent: true },
    { name: "close factor", key: "closeFactor", isPercent: true },
    {
      name: "liquidation incentive",
      key: "liquidationIncentive",
      isPercent: true,
    },
  ],
  univ3: [],
  crvv2: [],
};
